### ISSUE TITLE
Print a table

### ISSUE THREAD

**Issue by sakhi2028** [sakhi2028/SQA20f20618#1]
Can you please help me in printing a table of user entered number in c programming language?

**Comment by iqraa2026** [comment]
You can print a table by using below code:

Solution::

#include <stdio.h>
int main() {
  int n, i;
  printf("Enter an integer: ");
  scanf("%d", &n);
  for (i = 1; i <= 10; ++i) {
    printf("%d * %d = %d \n", n, i, n * i);
  }
  return 0;
}
